import json
import sys

# Correct absolute imports to align with your new src/ directory layout
from src.rag.embedder import IntentEmbedder
from src.rag.pinecone_store import PineconeStore


class WorkdayDispatcher:
    def __init__(self):
        print("Initializing Dispatcher...", file=sys.stderr)
        self.embedder = IntentEmbedder()
        self.store = PineconeStore()

    def route_query(self, user_query, namespace="workday_specs", top_k=1):
        """
        Takes a human question, searches Pinecone, and returns the API schema matching template.
        """
        print(f"Routing query: '{user_query}'...", file=sys.stderr)

        # 1. Turn the question into a mathematical vector representation
        query_vector = self.embedder.encode_intents(user_query)[0]

        # 2. Search the vector database
        results = self.store.query_intent(
            query_vector=query_vector,
            namespace=namespace,
            top_k=top_k
        )

        # 3. Parse and return the best match securely
        if not results or 'matches' not in results or not results['matches']:
            return {"error": "No matching API template found in vector database."}

        best_match = results['matches'][0]
        score = best_match.get('score', 0.0)
        
        # Defensive fallback if metadata block is completely absent or empty
        metadata = best_match.get('metadata') or {}
        
        # FIXED: Align lookups with the exact metadata fields generated by populate_db.py
        api_name = best_match.get('id', 'Unknown API')
        method = metadata.get('method', 'GET')
        path = metadata.get('path', '')

        print(
            f"Match found with {score:.2f} confidence: {api_name}",
            file=sys.stderr
        )

        # FIXED: Dynamically extract parameters out of the raw_openapi_spec block
        parameters = []
        raw_spec_str = metadata.get('raw_openapi_spec')
        if raw_spec_str:
            try:
                spec_json = json.loads(raw_spec_str)
                # Navigate the isolated spec tree: paths -> path -> method -> parameters
                paths_obj = spec_json.get("paths", {})
                path_obj = paths_obj.get(path, {})
                method_obj = path_obj.get(method.lower(), {})
                parameters = method_obj.get("parameters", [])
            except Exception as e:
                print(f"Warning parsing parameters from spec: {e}", file=sys.stderr)
                parameters = []

        return {
            "api_name": api_name,
            "method": method,
            "full_path": path,
            "path": path,  # Included for cross-compatibility with older router_tool contracts
            "parameters": parameters,
            "confidence_score": round(score, 4)
        }


if __name__ == "__main__":
    # Test the Dispatcher locally using execution context tools
    dispatcher = WorkdayDispatcher()

    print("\n--- Test 1 Running ---", file=sys.stderr)
    test_question_1 = "Give me the list of workers."
    result_1 = dispatcher.route_query(test_question_1)
    print(json.dumps(result_1, indent=2))